export const surpriseMePrompts = [
  'A cozy cabin in the woods with a crackling fireplace and snow falling outside',
  'A colorful marketplace in Marrakesh with exotic spices and vibrant textiles',
  'A quiet library with shelves filled with antique books and comfortable armchairs',
  'A beach on a sunny day with crystal-clear waters and palm trees swaying in the breeze',
  'A snowy mountain peak with stunning panoramic views and fresh mountain air',
  'A bustling city street at night with neon lights and busy crowds',
  'A vineyard with rows of grapevines and a charming farmhouse in the distance',
  'A peaceful Japanese garden with a serene pond and cherry blossom trees',
  'A safari adventure with wild animals grazing on the savanna',
  'A cozy bed and breakfast in a charming small town with a quaint main street',
  'A majestic castle with towering turrets and sweeping views of the surrounding countryside',
  'A luxurious spa with hot stone massages and calming aromatherapy',
  'A modern art gallery with innovative installations and interactive exhibits',
  'A romantic gondola ride through the canals of Venice at sunset',
  'A stunning natural wonder like the Grand Canyon or Niagara Falls',
  'A futuristic city with soaring skyscrapers and sleek, high-tech design',
  'A cozy mountain cabin with a wood-burning stove and a hot tub under the stars',
  'A historic landmark like the Eiffel Tower, the Colosseum, or the Great Wall of China',
  'A quaint seaside town with colorful houses and a bustling harbor',
  'A breathtaking hot air balloon ride over scenic countryside or a bustling city',
  'A serene hike through a peaceful forest with towering trees and babbling brooks',
  'A festive outdoor market with twinkling lights, holiday treats, and handmade gifts',
  'A tropical paradise with white sandy beaches, crystal-clear waters, and palm trees swaying in the breeze',
  'A cozy coffee shop with comfortable chairs, freshly brewed coffee, and homemade pastries',
  'A rustic farm with rolling hills, grazing cows, and a charming red barn',
  'A thrilling roller coaster ride at a bustling amusement park with friends and family',
  'A peaceful countryside drive with scenic views and quaint small towns',
  'An exciting night at the theater with a live performance of a beloved play or musical',
  'A quiet mountain lake with a wooden dock and a rowboat',
  'A lively concert with a favorite musician or band and a sea of dancing fans',
  'A colorful street art tour of a vibrant city with murals, graffiti, and hidden gems',
  'A day trip to a charming neighboring town with unique shops, restaurants, and attractions',
  'A dazzling fireworks display on the Fourth of July or New Year\'s Eve',
  'A romantic candlelit dinner at a fancy restaurant with a view',
  'A mysterious escape room challenge with puzzles, clues, and hidden objects',
  'A day at the beach with a cooler full of snacks, sunscreen, and a good book',
  'A thrilling skydiving or bungee jumping adventure with breathtaking views',
  'A cozy winter cabin with a roaring fire, a stack of board games, and mugs of hot cocoa',
  'A peaceful yoga retreat in a beautiful natural setting with daily meditation and healthy meals',
  'A festive outdoor ice skating rink with twinkling lights and holiday music',
  'A thrilling whitewater rafting adventure through rapids and rocky gorges',
  'A relaxing day at a natural hot springs with soothing mineral water and breathtaking views',
];
